name: Test Secret Logging

on:
  workflow_dispatch: # This enables manual triggering

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x test.sh

      - name: Run script with secret
        run: ./test.sh "${{ secrets.MY_SECRET }}"
